version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dockerfile
    ports:
      - "5000:5000"
  mysqldb:
    image: mysql
  app:
    build:
      context: .
      dockerfile: Dockerfile.dockerfile      
    image: node-mysql-app
    depends_on:
      - mysqldb